name: Build Client
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Pip Packages
        run: pip install -r requirements.txt

      - name: Run a Python script
        run: python generate_executable.py

      - uses: actions/upload-artifact@v3
        with:
          name: iq_sim_client_${{ matrix.os }} 
          path: iq_sim_client
          if-no-files-found: error
